version: 0.2

phases:
  install:
    commands:
      - echo "Instalando Node 21 e npm..."
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash -
      - sudo yum install -y nodejs
  build:
    commands:
      - echo "Instalando dependências do npm..."
      - npm install --loglevel=error
      - echo "Iniciando o build com variáveis de ambiente..."
      - REACT_APP_API_URL=$REACT_APP_API_URL SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - echo "Rodando testes unitários..."
      - npm test
  post_build:
    commands:
      - echo "Build finalizado!"
