FROM public.ecr.aws/docker/library/node:21-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --loglevel=error

COPY . .

ARG ENVIRONMENT
ENV REACT_APP_API_URL_PROD=https://prod.projeto-aws.com.br
ENV REACT_APP_API_URL_HOM=https://hom.projeto-aws.com.br


RUN if [ "$ENVIRONMENT" = "https://prod.projeto-aws.com.br" ]; then \
    echo "Using prod API URL"; \
    echo "REACT_APP_API_URL=${REACT_APP_API_URL_PROD}" >> .env; \
  else \
    echo "Using hom API URL"; \
    echo "REACT_APP_API_URL=${REACT_APP_API_URL_HOM}" >> .env; \
  fi

COPY .env /app/

RUN NODE_OPTIONS=--openssl-legacy-provider SKIP_PREFLIGHT_CHECK=true npm run build --prefix client

RUN mv client/build build && rm -rf client/* && mv build client/

EXPOSE 8080

CMD [ "npm", "start" ]