version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
  build:
    commands:
      - echo "Iniciado testes em $(date)"
      - npm install --loglevel=error
      - echo Rodando testes unitarios...
      - npm test